<?php

declare(strict_types=1);

namespace RocketRouter;

use RuntimeException;

final class RouteCache
{
    public function __construct(
        private readonly string $cacheFilePath,
    ) {
    }

    /**
     * @param RouteItem[] $routes
     */
    public function write(array $routes): void
    {
        $dir = dirname($this->cacheFilePath);
        if (!is_dir($dir) && !mkdir($dir, 0755, true) && !is_dir($dir)) {
            throw new RuntimeException("Cannot create cache directory: {$dir}");
        }

        $content = "<?php\n\n"
            . "// Auto-generated by RocketRouter — do not edit.\n\n"
            . "return " . var_export($routes, true) . ";\n";

        if (file_put_contents($this->cacheFilePath, $content, LOCK_EX) === false) {
            throw new RuntimeException("Failed to write cache file: {$this->cacheFilePath}");
        }
    }

    /**
     * @return RouteItem[]
     */
    public function read(): array
    {
        if (!file_exists($this->cacheFilePath)) {
            throw new RuntimeException("Route cache not found: {$this->cacheFilePath}");
        }

        return require $this->cacheFilePath;
    }

    public function exists(): bool
    {
        return file_exists($this->cacheFilePath);
    }
}
